---
:concurrency: 1
:queues:
  - default
  - mailers
  - alpine_falcons_web_app_development_default
  - alpine_falcons_web_app_development_mailers
  - alpine_falcons_web_app_production_default
  - alpine_falcons_web_app_production_mailers
